### ISSUE TITLE
refresh?

### ISSUE THREAD

**Issue by AlexECP** [gboyegadada/lumen-jwt#10]
Hi,

I see there is a refresh method in the Helper, but im not clear on when it is called? Does it refresh on every request? or?

**Comment by gboyegadada** [comment]
Hi @AlexECP, it is not called automatically. You have to call it by yourself just when the token is about to expire. You can check for this in a middleware on every request and refresh when needed. There's a very similar question [here](https://github.com/tymondesigns/jwt-auth/issues/872) with great tips on when to do a token refresh.

**Comment by AlexECP** [comment]
Thanks for the quick reply, I think I understand.
