### ISSUE TITLE
Users passing auth guard somethimes

### ISSUE THREAD

**Issue by SebastianBotez** [gboyegadada/lumen-jwt#15]
Can you provide some logic explanations about this? Dunno what to do honestly.
Some users are passing the auth guard using this JWT auth library and we receive sql errors. 

https://stackoverflow.com/questions/56679661/lumen-jwt-authentication-passes-the-guard

**Comment by gboyegadada** [comment]
Try:

    if(!Auth::check() || Auth::user() == NULL) {
        Auth::logout();
        return abort(401, 'Unauthorized.');
    }

Since `Auth:check()` returns `true` when user **is** authenticated so what you want is to abort if: 


> [ User is not authenticated ] OR [ User is `null` ]
