### ISSUE TITLE
JWT_EXPIRE_AFTER format?

### ISSUE THREAD

**Issue by SebastianBotez** [gboyegadada/lumen-jwt#16]
Hello guys.
My app logs out users after a certain period of time.
I tried to set JWT_EXPIRE_AFTER with a higher value but still doing this.
I was wondering what is the type that this parameter accepts? Milliseconds? Minutes? Hours?
I try to figure out how to make the token available for 1 month.

Thank you.

**Comment by gboyegadada** [comment]
Hey @SebastianBotez ! The parameter accepts a unix timestamp (like PHP `time()`).

This library uses [`firebase/php-jwt`](https://github.com/firebase/php-jwt) as a dependency. You can take a look at how the field is used [here](https://github.com/firebase/php-jwt/blob/feb0e820b8436873675fd3aca04f3728eb2185cb/src/JWT.php#L142).

**Comment by SebastianBotez** [comment]
Makes sense now.
Thank you very much. Really appreciate your response.
