### ISSUE TITLE
Can I change the token check method?

### ISSUE THREAD

**Issue by wtwei** [gboyegadada/lumen-jwt#3]
Hello, thank you for improving the expansion pack.
Token validation can use redis instead of using database queries.

**Comment by gboyegadada** [comment]
Hi @wtwei, token validation isn't done using the database (as JWT tokens work without having to do this). However I looked [here](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Auth/GuardHelpers.php) and saw that `Auth::check()` would still fetch an instance of the user from the db unnecessarily so I've pushed a new commit to fix that by making sure, for user status, we only check to see if our JWT token is valid and we only query the database when we actually do need to fetch an instance of the user.
