### ISSUE TITLE
Error on request after generating JWT token

### ISSUE THREAD

**Issue by SebastianBotez** [gboyegadada/lumen-jwt#7]
The issue reproduce steps:
1. I`m doing a request to my API to generate the JWT token
2. The server responds and gives me the generated token.
3. I'm doing another request just after using it for authorization. 

The token is not recognised but if I'm doing the request again after 5 seconds, the token is recognised.

It seems that the generated token it`s not able to be decoded within 5 seconds after generation.

**Comment by gboyegadada** [comment]
Hi Sebastian, you can set the delay in seconds by adding `JWT_NBF_DELAY=5`
to your `.env` file (the default is 5 seconds).

**Comment by gboyegadada** [comment]
Hi Sebastian, you can set the delay in seconds by adding `JWT_NBF_DELAY=5` to your `.env` file (the default is 5 seconds).

**Comment by SebastianBotez** [comment]
Thank you very much, this solved the problem. Best regards.
