### ISSUE TITLE
JWTguard.php, protected $user inherited, error

### ISSUE THREAD

**Issue by SebastianBotez** [gboyegadada/lumen-jwt#8]
Yega\Auth\JWTGuard and Illuminate\Auth\GuardHelpers define the same property ($user) in the composition of Yega\Auth\JWTGuard. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed

This error appears when I try to to acces any endpoint that is protected by the middleware.
If I delete the variable from that file, it works fine but when we deploy, we need to do composer install so, we have to remove it again.

The $user it's double defined I supose.

I use Lumen 5.4

**Comment by gboyegadada** [comment]
Hi @SebastianBotez , thanks for pointing this out. I've removed the double and done a new push. Cheers!
